# Generated by Django 4.2 on 2026-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
