# Generated by Django 4.2 on 2026-04-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0005_doctors_end_time_doctors_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
