# Generated by Django 4.2 on 2026-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0008_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
