# Generated by Django 4.2 on 2026-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0009_doctors_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
