# Generated by Django 4.2 on 2026-04-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0011_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='available_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
