# Generated by Django 4.2 on 2026-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0012_doctors_available_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='view_count',
        ),
        migrations.AddField(
            model_name='doctors',
            name='available_time_slots',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='available_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
