# Generated by Django 4.2 on 2026-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0013_remove_doctors_end_time_remove_doctors_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='available_time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
