# Generated by Django 4.2 on 2026-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0014_alter_doctors_available_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
