# Generated by Django 4.2 on 2026-05-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0016_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'doctors', 'appointment_date')},
        ),
    ]
