# Generated by Django 4.2 on 2026-05-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0017_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
