# Generated by Django 4.2 on 2026-05-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0018_doctors_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
